# Generated by Django 3.1a1 on 2020-07-08 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_gene_used_in_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
