# Generated by Django 3.1a1 on 2020-07-08 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_batch_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='reports')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cookbook_report',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='batch',
            name='report',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='cookbook.report'),
        ),
    ]
