# Generated by Django 3.1a1 on 2020-07-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_auto_20200708_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='cookbook.batch'),
        ),
    ]
