# Generated by Django 3.1a1 on 2020-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20200710_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchitem',
            options={'managed': True, 'ordering': ['ingredient__nature__name']},
        ),
        migrations.AddField(
            model_name='nature',
            name='order_nbr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
