# Generated by Django 3.1a1 on 2020-06-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menu_gui_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='gui_menu',
        ),
    ]
