# Generated by Django 3.1a1 on 2020-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_menu_gui_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='gui_menu',
            field=models.BooleanField(default=False),
        ),
    ]
